name: 'mainline-base-ref'
description: 'Find the latest base commit on the default branch for a pull request'
author: 'Simon Menke'
inputs:
  github_token:
    required: true
    description: "The GITHUB_TOKEN"
outputs:
  mainline_ref:
    description: The name of the default branch
  mainline_sha:
    description: The SHA of the commit on the default branch
runs:
  using: 'node12'
  main: 'dist/index.js'
